name: Multipass
description: Multipass GUI application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  async: ^2.10.0
  basics: ^0.10.0
  built_collection: ^5.1.1
  collection: ^1.17.0
  data_table_2: ^2.3.12
  flutter:
    sdk: flutter
  flutter_pty: ^0.3.1
  flutter_riverpod: ^2.2.0
  flutter_svg: ^2.0.4
  grpc: ^3.1.0
  protobuf: ^2.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  window_manager: ^0.3.1
  xterm: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/Ubuntu-R.ttf
        - asset: assets/Ubuntu-B.ttf
          weight: 700